# Use the Centos image as the base image.
FROM centos

# Allow yum to be used to install applications in the Centos image
RUN cd /etc/yum.repos.d/ && \
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

# Install dependencies for protoc and the military symbology service
RUN yum -y install libatomic && \
    yum -y install fontconfig && \
    yum -y install nmap-ncat && \
    yum clean all

# # Define expected volume mount points for External Dir, src, launchProcess.xml
# VOLUME ["/mil/external", "/mil","/mil/launchProcess.xml"]

# Explicitly create the config directory
RUN mkdir -p /mil/entry
RUN mkdir -p /mil/launch
RUN mkdir -p /config
RUN mkdir -p /generated
RUN mkdir -p /temp
# Set working directory for container
WORKDIR /mil

# Below line is being overwritten while mounting /mil/config/launchProcess.xml during run time. Also launchProcess.sh isn't being used anywher, so REMOVE it.
COPY scripts/dev-tools/Linux/GIFT/scripts/util/launchProcess /mil/launch
# COPY scripts/util/launchProcess.xml /app/ --> this will be a volume now so not req to COPY
COPY entrypoint.sh /mil/entry
COPY /config /config
# Make entrypoint.sh executable
RUN chmod +x /mil/entry/entrypoint.sh

# Default command to run when the container starts
ENTRYPOINT ["/mil/entry/entrypoint.sh"]
CMD ["start", "ped"]
